### ISSUE TITLE
Saving an image with `DO rust+CARGO` as `ENTRYPOINT`

### ISSUE THREAD

**Issue by JohnCMoon** [earthly/lib#51]
I have a unit test which depends on an external postgres database to run. With GitLab CI, I'm able to run the test like this:

```yaml
unit-test:
  ...
  variables:
    POSTGRES_DB: keylay-test
    POSTGRES_USER: keylay
    POSTGRES_PASSWORD: keylay
  services:
    - postgres:latest
  script:
    - >
      KEYLAY_TEST_DATABASE_URL="postgres://keylay:keylay@postgres/keylay-test"
      cargo test --release --frozen --offline --features postgres
```

I'm trying to figure out how to express the same test with Earthly (using `lib/rust`). I understand how to use `WITH DOCKER` to start up services, but I'm not sure how to run `cargo test` in that context.

If I were dealing with the `cargo` commands directly, I could do something like this at the end of my binary build container:

```dockerfile
ENTRYPOINT ["cargo", "test", ... "--features", "postgres"]
SAVE IMAGE cargo-test:postgres
```
And then run the resultant container in the `WITH DOCKER` context alongside the `postgres` container, but I don't see a way to do that. I realize this may be an odd use case, but I'm curious if there's an existing solution. If not, I'd be happy to help work on a solution!
